version: '3.1'

services:
  frontend:
    build: ./DS-Estate-Front
    container_name: ds-estate-frontend
    ports:
      - "8000:8000"
    volumes:
      - ./DS-Estate-Front:/app
  backend:
    build: ./DS-Estate-Back
    container_name: ds-estate-backend
    ports:
      - "5000:5000"
    volumes:
      - ./DS-Estate-Back:/app

    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: booking_app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/populate.sql


volumes:
  db_data: